# Results

## Setup

In [1]:
import pandas as pd

ROUND1INCR = 1
ROUND2INCR = 2
ROUND3INCR = 4
ROUND4INCR = 8
ROUND5INCR = 16
ROUND6INCR = 32

actualTeams2026 = {
    1: ["Duke", "Arizona", "Florida", "Michigan"],
    2: ["Connecticut", "Purdue", "Houston", "Iowa St"],
    3: ["Michigan St", "Gonzaga", "Illinois", "Virginia"],
    4: ["Kansas", "Arkansas", "Nebraska", "Alabama"],
    5: ["St John's", "Wisconsin", "Vanderbilt", "Texas Tech"],
    6: ["Louisville", "Texas", "North Carolina", "Tennessee"],
    7: ["UCLA", "Miami FL", "St Mary's CA", "Kentucky"],
    8: ["Ohio St", "Utah St", "Iowa", "Georgia"],
    9: ["TCU", "Villanova", "Clemson", "St Louis"],
    10: ["UCF", "Missouri", "Texas A&M", "Santa Clara"],
    11: ["South Florida", "BYU", "VCU", "Miami OH"],
    12: ["Northern Iowa", "High Point", "McNeese St", "Akron"],
    13: ["Cal Baptist", "Hawaii", "Troy", "Hofstra"],
    14: ["N Dakota St", "Kennesaw", "Penn", "Wright St"],
    15: ["Furman", "Queens NC", "Idaho", "Tennessee St"],
    16: ["Siena", "LIU Brooklyn", "Prairie View", "Howard"],
}

### First Round

In [2]:
matchup1CSV = pd.read_csv("firstRoundMatchups.csv")
display(matchup1CSV.head())

   Year  WinnerID  LoserID
0  2026      1181     1373
1  2026      1395     1326
2  2026      1385     1320
3  2026      1242     1465
4  2026      1257     1378

In [3]:
predictionsCSV = pd.read_csv("../MTourneyPredictions.csv")
teamsCSV = pd.read_csv("../data/mens/MTeams.csv")

teamNames: dict[int, str] = dict[int, str](
    zip(teamsCSV["TeamID"].astype(int), teamsCSV["TeamName"].astype(str))
)

predictionPairs: set[tuple[int, int]] = set[tuple[int, int]](
    zip(
        predictionsCSV["WTeamID"].astype(int),
        predictionsCSV["LTeamID"].astype(int),
    )
)
round1Results = []
round1Points = 0

for _, row in matchup1CSV.iterrows():
    winnerID = int(row["WinnerID"])
    loserID = int(row["LoserID"])

    if (winnerID, loserID) in predictionPairs:
        correct = True
        predictedWinnerID = winnerID
        pointsEarned = ROUND1INCR
    elif (loserID, winnerID) in predictionPairs:
        correct = False
        predictedWinnerID = loserID
        pointsEarned = 0
    else:
        correct = False
        predictedWinnerID = None
        pointsEarned = 0

    round1Points += pointsEarned
    round1Results.append({
        "Winner": teamNames[winnerID],
        "Loser": teamNames[loserID],
        "YourPick": teamNames[predictedWinnerID] if predictedWinnerID is not None else "Missing",
        "Correct": correct,
        "PointsEarned": pointsEarned,
    })

round1ResultsCSV = pd.DataFrame(round1Results)
display(round1ResultsCSV.head())
print(f"First round points: {round1Points}")

       Winner          Loser       YourPick  Correct  PointsEarned
0        Duke          Siena           Duke     True             1
1         TCU        Ohio St            TCU     True             1
2   St John's  Northern Iowa      St John's     True             1
3      Kansas    Cal Baptist         Kansas     True             1
4  Louisville  South Florida  South Florida    False             0

First round points: 26

### Second Round

In [4]:
matchup2CSV = pd.read_csv("secondRoundMatchups.csv")
display(matchup2CSV.head())

   Year  WinnerID  LoserID
0  2026      1181     1395
1  2026      1385     1242
2  2026      1277     1257
3  2026      1163     1417
4  2026      1234     1196

In [6]:
predictionsCSV = pd.read_csv("../MTourneyPredictions.csv")
teamsCSV = pd.read_csv("../data/mens/MTeams.csv")

teamNames: dict[int, str] = dict[int, str](
    zip(teamsCSV["TeamID"].astype(int), teamsCSV["TeamName"].astype(str))
)

predictionPairs: set[tuple[int, int]] = set[tuple[int, int]](
    zip(
        predictionsCSV["WTeamID"].astype(int),
        predictionsCSV["LTeamID"].astype(int),
    )
)
round2Results = []
round2Points = 0

for _, row in matchup2CSV.iterrows():
    winnerID = int(row["WinnerID"])
    loserID = int(row["LoserID"])

    if (winnerID, loserID) in predictionPairs:
        correct = True
        predictedWinnerID = winnerID
        pointsEarned = ROUND2INCR
    elif (loserID, winnerID) in predictionPairs:
        correct = False
        predictedWinnerID = loserID
        pointsEarned = 0
    else:
        correct = False
        predictedWinnerID = None
        pointsEarned = 0

    round2Points += pointsEarned
    round2Results.append({
        "Winner": teamNames[winnerID],
        "Loser": teamNames[loserID],
        "YourPick": teamNames[predictedWinnerID] if predictedWinnerID is not None else "Missing",
        "Correct": correct,
        "PointsEarned": pointsEarned,
    })

round2ResultsCSV = pd.DataFrame(round2Results)
display(round2ResultsCSV)
print(f"Second round points: {round2Points}")

         Winner       Loser     YourPick  Correct  PointsEarned
0          Duke         TCU         Duke     True             2
1     St John's      Kansas       Kansas    False             0
2   Michigan St  Louisville   Louisville    False             0
3   Connecticut        UCLA  Connecticut     True             2
4          Iowa     Florida      Florida    False             0
5      Nebraska  Vanderbilt     Nebraska     True             2
6      Illinois         VCU     Illinois     True             2
7       Houston   Texas A&M      Houston     True             2
8       Arizona     Utah St      Arizona     True             2
9      Arkansas   Wisconsin     Arkansas     True             2
10      Gonzaga       Texas      Gonzaga     True             2
11       Purdue    Miami FL       Purdue     True             2
12     Michigan    St Louis     Michigan     True             2
13      Alabama  Texas Tech   Texas Tech    False             0
14    Tennessee    Virginia     Virginia    False             0
15      Iowa St    Kentucky      Iowa St     True             2

Second round points: 22

### Round of 16

In [ ]:
matchup3CSV = pd.read_csv("thirdRoundMatchups.csv")
display(matchup3CSV.head())

In [ ]:
predictionsCSV = pd.read_csv("../MTourneyPredictions.csv")
teamsCSV = pd.read_csv("../data/mens/MTeams.csv")

teamNames: dict[int, str] = dict[int, str](
    zip(teamsCSV["TeamID"].astype(int), teamsCSV["TeamName"].astype(str))
)

predictionPairs: set[tuple[int, int]] = set[tuple[int, int]](
    zip(
        predictionsCSV["WTeamID"].astype(int),
        predictionsCSV["LTeamID"].astype(int),
    )
)
round3Results = []
round3Points = 0

for _, row in matchup3CSV.iterrows():
    winnerID = int(row["WinnerID"])
    loserID = int(row["LoserID"])

    if (winnerID, loserID) in predictionPairs:
        correct = True
        predictedWinnerID = winnerID
        pointsEarned = ROUND3INCR
    elif (loserID, winnerID) in predictionPairs:
        correct = False
        predictedWinnerID = loserID
        pointsEarned = 0
    else:
        correct = False
        predictedWinnerID = None
        pointsEarned = 0

    round3Points += pointsEarned
    round3Results.append({
        "Winner": teamNames[winnerID],
        "Loser": teamNames[loserID],
        "YourPick": teamNames[predictedWinnerID] if predictedWinnerID is not None else "Missing",
        "Correct": correct,
        "PointsEarned": pointsEarned,
    })

round3ResultsCSV = pd.DataFrame(round3Results)
display(round3ResultsCSV.head())
print(f"Round of 16 points: {round3Points}")

### Elite Eight

In [ ]:
matchup4CSV = pd.read_csv("fourthRoundMatchups.csv")
display(matchup4CSV.head())

In [ ]:
predictionsCSV = pd.read_csv("../MTourneyPredictions.csv")
teamsCSV = pd.read_csv("../data/mens/MTeams.csv")

teamNames: dict[int, str] = dict[int, str](
    zip(teamsCSV["TeamID"].astype(int), teamsCSV["TeamName"].astype(str))
)

predictionPairs: set[tuple[int, int]] = set[tuple[int, int]](
    zip(
        predictionsCSV["WTeamID"].astype(int),
        predictionsCSV["LTeamID"].astype(int),
    )
)
round4Results = []
round4Points = 0

for _, row in matchup4CSV.iterrows():
    winnerID = int(row["WinnerID"])
    loserID = int(row["LoserID"])

    if (winnerID, loserID) in predictionPairs:
        correct = True
        predictedWinnerID = winnerID
        pointsEarned = ROUND4INCR
    elif (loserID, winnerID) in predictionPairs:
        correct = False
        predictedWinnerID = loserID
        pointsEarned = 0
    else:
        correct = False
        predictedWinnerID = None
        pointsEarned = 0

    round4Points += pointsEarned
    round4Results.append({
        "Winner": teamNames[winnerID],
        "Loser": teamNames[loserID],
        "YourPick": teamNames[predictedWinnerID] if predictedWinnerID is not None else "Missing",
        "Correct": correct,
        "PointsEarned": pointsEarned,
    })

round4ResultsCSV = pd.DataFrame(round4Results)
display(round4ResultsCSV.head())
print(f"Elite Eight points: {round4Points}")

### Final Four

In [ ]:
matchup5CSV = pd.read_csv("fifthRoundMatchups.csv")
display(matchup5CSV.head())

In [ ]:
predictionsCSV = pd.read_csv("../MTourneyPredictions.csv")
teamsCSV = pd.read_csv("../data/mens/MTeams.csv")

teamNames: dict[int, str] = dict[int, str](
    zip(teamsCSV["TeamID"].astype(int), teamsCSV["TeamName"].astype(str))
)

predictionPairs: set[tuple[int, int]] = set[tuple[int, int]](
    zip(
        predictionsCSV["WTeamID"].astype(int),
        predictionsCSV["LTeamID"].astype(int),
    )
)
round5Results = []
round5Points = 0

for _, row in matchup5CSV.iterrows():
    winnerID = int(row["WinnerID"])
    loserID = int(row["LoserID"])

    if (winnerID, loserID) in predictionPairs:
        correct = True
        predictedWinnerID = winnerID
        pointsEarned = ROUND5INCR
    elif (loserID, winnerID) in predictionPairs:
        correct = False
        predictedWinnerID = loserID
        pointsEarned = 0
    else:
        correct = False
        predictedWinnerID = None
        pointsEarned = 0

    round5Points += pointsEarned
    round5Results.append({
        "Winner": teamNames[winnerID],
        "Loser": teamNames[loserID],
        "YourPick": teamNames[predictedWinnerID] if predictedWinnerID is not None else "Missing",
        "Correct": correct,
        "PointsEarned": pointsEarned,
    })

round5ResultsCSV = pd.DataFrame(round5Results)
display(round5ResultsCSV.head())
print(f"Final Four points: {round5Points}")

### National Championship

In [ ]:
matchup6CSV = pd.read_csv("sixthRoundMatchups.csv")
display(matchup6CSV.head())

In [ ]:
predictionsCSV = pd.read_csv("../MTourneyPredictions.csv")
teamsCSV = pd.read_csv("../data/mens/MTeams.csv")

teamNames: dict[int, str] = dict[int, str](
    zip(teamsCSV["TeamID"].astype(int), teamsCSV["TeamName"].astype(str))
)

predictionPairs: set[tuple[int, int]] = set[tuple[int, int]](
    zip(
        predictionsCSV["WTeamID"].astype(int),
        predictionsCSV["LTeamID"].astype(int),
    )
)
round6Results = []
round6Points = 0

for _, row in matchup6CSV.iterrows():
    winnerID = int(row["WinnerID"])
    loserID = int(row["LoserID"])

    if (winnerID, loserID) in predictionPairs:
        correct = True
        predictedWinnerID = winnerID
        pointsEarned = ROUND6INCR
    elif (loserID, winnerID) in predictionPairs:
        correct = False
        predictedWinnerID = loserID
        pointsEarned = 0
    else:
        correct = False
        predictedWinnerID = None
        pointsEarned = 0

    round6Points += pointsEarned
    round6Results.append({
        "Winner": teamNames[winnerID],
        "Loser": teamNames[loserID],
        "YourPick": teamNames[predictedWinnerID] if predictedWinnerID is not None else "Missing",
        "Correct": correct,
        "PointsEarned": pointsEarned,
    })

round6ResultsCSV = pd.DataFrame(round6Results)
display(round6ResultsCSV.head())
print(f"National Championship points: {round6Points}")